import PropTypes from "prop-types";
import React from "react";
// import { useMergeState } from "../../Helpers/customHooks";


const lotAssignments = [
  {
    "createdBy": "service-account-internal",
    "createdDate": "2022-04-21T13:10:05.336Z",
    "lastModifiedBy": "service-account-internal",
    "lastModifiedDate": "2022-04-21T13:10:05.336Z",
    "id": 109823,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "PLANNED",
    "plannedQuantity": 640,
    "actualQuantity": 0,
    "surplusQuantity": 0,
    "failureQuantity": 0,
    "dueDate": "2022-04-13T21:45:00Z",
    "plannedStart": "2022-04-27T05:40:00Z",
    "plannedEnd": "2022-04-27T09:46:00Z",
    "actualStart": null,
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": false,
    "orderNumber": "559701",
    "orderSequence": null,
    "workStep": 1,
    "changeOverDuration": null,
    "updatedStartTime": "2022-04-27T05:40:00Z",
    "updatedEndTime": "2022-04-27T09:46:00Z",
    "stateChangeTimeStamp": null,
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-03-02T09:05:28Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2022-04-21T10:26:08Z",
      "id": 4,
      "lineId": "EL11 (1)",
      "name": "EL11 (1)",
      "description": "EL11 (1)",
      "active": true,
      "minFifo": null,
      "maxFifo": null,
      "sourceId": "-3",
      "erpId": "",
      "externalPlanning": true,
      "checkByStorageTypeId": false,
      "storageTypeId": null,
      "uuid": "7b7e5b04-3753-40e2-9889-b1a4c2c4f754",
      "materialOrderService": true,
      "isDeleted": false,
      "productionVersion": " ",
      "productionSupplyAreas": null,
      "currentPlant": {
        "createdBy": "admin",
        "createdDate": "2020-03-02T08:49:29Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-04-01T10:43:31Z",
        "id": 1,
        "mesEP": "Sz0vm292.de.bosch.com:5672",
        "plantId": "szp",
        "productionProcess": "MTS",
        "name": "Salzgitter",
        "code": "123",
        "businessUnit": null,
        "erpId": "P72",
        "uuid": "6b848f68-7f1e-4742-99ac-a1a5d6a4a78c",
        "isDeleted": false,
        "npkRounding": false,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "admin",
        "createdDate": "2020-03-02T08:51:22Z",
        "lastModifiedBy": "admin",
        "lastModifiedDate": "2022-02-10T09:55:39Z",
        "id": 2,
        "identifier": "FAMS1",
        "address": "FAMS1",
        "name": "FAMS1",
        "active": true,
        "generatePackagingOrders": true,
        "uuid": "53252197-716a-49d8-be55-486ed44fb7d9",
        "isDeleted": false,
        "plant": {
          "createdBy": "admin",
          "createdDate": "2020-03-02T08:49:29Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-04-01T10:43:31Z",
          "id": 1,
          "mesEP": "Sz0vm292.de.bosch.com:5672",
          "plantId": "szp",
          "productionProcess": "MTS",
          "name": "Salzgitter",
          "code": "123",
          "businessUnit": null,
          "erpId": "P72",
          "uuid": "6b848f68-7f1e-4742-99ac-a1a5d6a4a78c",
          "isDeleted": false,
          "npkRounding": false,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": null,
      "destinationProductionSupplyArea": null,
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "PLANNED",
    "confirmedUnplanned": null,
    "manualPullDecision": null,
    "product": {
      "createdBy": "sys",
      "createdDate": "2020-11-20T10:41:36Z",
      "lastModifiedBy": "sys",
      "lastModifiedDate": "2020-11-20T10:41:36Z",
      "id": 24537,
      "partNumber": "0261S22365125",
      "description": "EL-STEUERGERÄT; MED17.1.27",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": 1,
      "panelSize": null,
      "packagingMaterial": null,
      "packagingSize": null,
      "targetTime": null,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": null,
      "quantityUnit": null,
      "materialType": null,
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": {
      "createdBy": "service-account-internal",
      "createdDate": "2022-04-21T13:10:05.376Z",
      "lastModifiedBy": "service-account-internal",
      "lastModifiedDate": "2022-04-21T13:10:05.376Z",
      "id": 18470,
      "targetKanbanQuantity": 1,
      "currentKanbanQuantity": 0,
      "targetTime": null,
      "lotFormationStatus": null,
      "remainingQuantity": null,
      "levKanbanQuantity": null,
      "supKanbanQuantity": null,
      "partNumber": {
        "createdBy": "sys",
        "createdDate": "2020-11-20T10:41:36Z",
        "lastModifiedBy": "sys",
        "lastModifiedDate": "2020-11-20T10:41:36Z",
        "id": 24537,
        "partNumber": "0261S22365125",
        "description": "EL-STEUERGERÄT; MED17.1.27",
        "replenishmentType": null,
        "numberPerKanban": null,
        "kanbanQuantity": null,
        "lotSize": 1,
        "panelSize": null,
        "packagingMaterial": null,
        "packagingSize": null,
        "targetTime": null,
        "planningTime": null,
        "colorCode": null,
        "customer": null,
        "active": true,
        "isMaterialOrdering": false,
        "baseUnitOfMeasure": null,
        "quantityUnit": null,
        "materialType": null,
        "productFamily": null,
        "productIdentification": null,
        "stock": null
      }
    },
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 14760000,
    "entityType": "lot",
    "producedQuantity": 0
  },
  {
    "createdBy": "admin",
    "createdDate": "2022-04-15T09:53:48Z",
    "lastModifiedBy": "admin",
    "lastModifiedDate": "2022-04-20T10:29:41.740Z",
    "id": 109733,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "PLANNED",
    "plannedQuantity": 251,
    "actualQuantity": 0,
    "surplusQuantity": 0,
    "failureQuantity": 0,
    "dueDate": "2020-03-07T02:13:00Z",
    "plannedStart": "2020-03-07T02:13:00Z",
    "plannedEnd": "2020-03-07T04:03:00Z",
    "actualStart": null,
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": false,
    "orderNumber": "855936/251",
    "orderSequence": null,
    "workStep": null,
    "changeOverDuration": null,
    "updatedStartTime": "2022-04-20T17:48:41.736Z",
    "updatedEndTime": "2022-04-20T19:38:41.736Z",
    "stateChangeTimeStamp": null,
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-03-02T09:18:50Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2022-04-20T06:09:22Z",
      "id": 6,
      "lineId": "FA1.1(1)",
      "name": "FAMS1.1.1",
      "description": "FA1.1(1)",
      "active": true,
      "minFifo": null,
      "maxFifo": null,
      "sourceId": "110",
      "erpId": "",
      "externalPlanning": true,
      "checkByStorageTypeId": false,
      "storageTypeId": null,
      "uuid": "b3c1373f-77ec-47d1-9f1a-b64c5f34b00b",
      "materialOrderService": true,
      "isDeleted": false,
      "productionVersion": " ",
      "productionSupplyAreas": null,
      "currentPlant": {
        "createdBy": "admin",
        "createdDate": "2020-03-02T08:49:29Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-04-01T10:43:31Z",
        "id": 1,
        "mesEP": "Sz0vm292.de.bosch.com:5672",
        "plantId": "szp",
        "productionProcess": "MTS",
        "name": "Salzgitter",
        "code": "123",
        "businessUnit": null,
        "erpId": "P72",
        "uuid": "6b848f68-7f1e-4742-99ac-a1a5d6a4a78c",
        "isDeleted": false,
        "npkRounding": false,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "admin",
        "createdDate": "2020-03-02T08:51:22Z",
        "lastModifiedBy": "admin",
        "lastModifiedDate": "2022-02-10T09:55:39Z",
        "id": 2,
        "identifier": "FAMS1",
        "address": "FAMS1",
        "name": "FAMS1",
        "active": true,
        "generatePackagingOrders": true,
        "uuid": "53252197-716a-49d8-be55-486ed44fb7d9",
        "isDeleted": false,
        "plant": {
          "createdBy": "admin",
          "createdDate": "2020-03-02T08:49:29Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-04-01T10:43:31Z",
          "id": 1,
          "mesEP": "Sz0vm292.de.bosch.com:5672",
          "plantId": "szp",
          "productionProcess": "MTS",
          "name": "Salzgitter",
          "code": "123",
          "businessUnit": null,
          "erpId": "P72",
          "uuid": "6b848f68-7f1e-4742-99ac-a1a5d6a4a78c",
          "isDeleted": false,
          "npkRounding": false,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": null,
      "destinationProductionSupplyArea": null,
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "AUTOMATIC_BACKLOG",
    "confirmedUnplanned": null,
    "manualPullDecision": null,
    "product": {
      "createdBy": "admin",
      "createdDate": "2020-03-02T10:45:35Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2022-04-12T12:03:03Z",
      "id": 9392,
      "partNumber": "0281036954133",
      "description": "EL CONTROL UNIT; MD1CP002",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": 1,
      "panelSize": null,
      "packagingMaterial": "0281036954133",
      "packagingSize": null,
      "targetTime": 0,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": "ST",
      "quantityUnit": "PIECE",
      "materialType": "FERT",
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": null,
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 6600000,
    "entityType": "lot",
    "producedQuantity": 0
  }
];


export const getFormatedData = () => {
  const newData = lotAssignments.map((x, i) => Object.assign(x, {
    lotNetId: 3008202201,
    erpIdentifier: "Test-SmartID",
    lotAssignmentStatus: "PLANNED",
    id: null
  }));
  console.log({ newData });
  return newData;
};

// const MyCompo = (props) => {
//   const [state, setState] = useMergeState({
//     data: [],
//   });
//   const { className } = props;
//   const onChange = (key, value) => {
//     setState({ [key]: value });
//   };
//   return (
//     <div className={classnames("-wrapper", className)}>
//       <span>my component</span>
//     </div>
//   );
// };
// MyCompo.defaultProps = {
//   className: "",
// };
// MyCompo.propTypes = {
//   className: PropTypes.string,
// };

// export default MyCompo;
