import classnames from "classnames";
import PropTypes from "prop-types";
import React from "react";
import { useMergeState } from "../../Helpers/customHooks";


const lotAssignments = [
  {
    "createdBy": "admin",
    "createdDate": "2020-09-24T08:58:58Z",
    "lastModifiedBy": "admin",
    "lastModifiedDate": "2020-09-24T08:58:58Z",
    "id": 26456,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "IN_PREPARATION",
    "plannedQuantity": 238,
    "actualQuantity": null,
    "surplusQuantity": 0,
    "failureQuantity": null,
    "dueDate": "2020-09-27T08:58:58Z",
    "plannedStart": "2020-09-24T08:58:58Z",
    "plannedEnd": "2020-09-27T08:58:58Z",
    "actualStart": null,
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": true,
    "orderNumber": null,
    "orderSequence": null,
    "workStep": null,
    "changeOverDuration": null,
    "updatedStartTime": null,
    "updatedEndTime": null,
    "stateChangeTimeStamp": null,
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-09-24T08:58:52Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2021-10-28T10:53:35Z",
      "id": 95,
      "lineId": "line 2",
      "name": "line 2",
      "description": "Benchmark Line line 2",
      "active": true,
      "minFifo": 0,
      "maxFifo": 0,
      "sourceId": "line 2",
      "erpId": "",
      "externalPlanning": true,
      "checkByStorageTypeId": null,
      "storageTypeId": null,
      "uuid": "3d250362-969e-4714-bcba-6a52096ee97d",
      "materialOrderService": false,
      "isDeleted": true,
      "productionVersion": "",
      "productionSupplyAreas": [
        {
          "createdBy": "admin",
          "createdDate": "2020-04-29T04:01:17Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2021-10-28T10:53:38Z",
          "id": 1,
          "storageBinId": "PVB580_edited_131",
          "storageTypeId": null,
          "uuid": "faebfc42-b7e2-46f6-8ccf-ea653aed3eb6",
          "isDeleted": true
        }
      ],
      "currentPlant": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:18Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-02-21T11:00:53Z",
        "id": 3,
        "mesEP": "",
        "plantId": "BHP",
        "productionProcess": "MTS",
        "name": "Docker Swarm BHP",
        "code": "Test",
        "businessUnit": null,
        "erpId": "6230",
        "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
        "isDeleted": false,
        "npkRounding": true,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:20Z",
        "lastModifiedBy": "admin",
        "lastModifiedDate": "2022-05-31T09:42:19Z",
        "id": 114,
        "identifier": "050 321V",
        "address": "",
        "name": "050 321VXX",
        "active": true,
        "generatePackagingOrders": false,
        "uuid": "aaaa6d67-148a-41de-a906-42060b0db81c",
        "isDeleted": false,
        "plant": {
          "createdBy": "system",
          "createdDate": "2020-08-27T08:41:18Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-02-21T11:00:53Z",
          "id": 3,
          "mesEP": "",
          "plantId": "BHP",
          "productionProcess": "MTS",
          "name": "Docker Swarm BHP",
          "code": "Test",
          "businessUnit": null,
          "erpId": "6230",
          "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
          "isDeleted": false,
          "npkRounding": true,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": [],
      "destinationProductionSupplyArea": null,
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "PLANNED",
    "confirmedUnplanned": null,
    "manualPullDecision": "NONE",
    "product": {
      "createdBy": "admin",
      "createdDate": "2020-02-10T15:29:13Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2020-08-22T12:29:42Z",
      "id": 1236,
      "partNumber": "0261S1020A21B",
      "description": "EL-STEUERGERÄT; MG1CS201",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": null,
      "panelSize": null,
      "packagingMaterial": "0261S1020A21B",
      "packagingSize": null,
      "targetTime": 0,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": null,
      "quantityUnit": null,
      "materialType": null,
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": null,
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 259200000,
    "producedQuantity": 0,
    "entityType": "lot"
  },
  {
    "createdBy": "admin",
    "createdDate": "2020-09-24T14:01:17Z",
    "lastModifiedBy": "system",
    "lastModifiedDate": "2020-09-24T14:52:10Z",
    "id": 26463,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "IN_PRODUCTION",
    "plannedQuantity": 194,
    "actualQuantity": 269,
    "surplusQuantity": 0,
    "failureQuantity": null,
    "dueDate": "2020-09-29T14:01:17Z",
    "plannedStart": "2020-09-24T14:01:17Z",
    "plannedEnd": "2020-09-29T14:01:17Z",
    "actualStart": "2020-09-24T14:05:09Z",
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": true,
    "orderNumber": null,
    "orderSequence": null,
    "workStep": null,
    "changeOverDuration": null,
    "updatedStartTime": "2020-09-24T14:05:09Z",
    "updatedEndTime": "2020-09-29T14:01:19Z",
    "stateChangeTimeStamp": "2020-09-24T14:01:20Z",
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-09-24T08:58:52Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2021-10-28T10:53:35Z",
      "id": 95,
      "lineId": "line 2",
      "name": "line 2",
      "description": "Benchmark Line line 2",
      "active": true,
      "minFifo": 0,
      "maxFifo": 0,
      "sourceId": "line 2",
      "erpId": "",
      "externalPlanning": true,
      "checkByStorageTypeId": null,
      "storageTypeId": null,
      "uuid": "3d250362-969e-4714-bcba-6a52096ee97d",
      "materialOrderService": false,
      "isDeleted": true,
      "productionVersion": "",
      "productionSupplyAreas": [
        {
          "createdBy": "admin",
          "createdDate": "2020-04-29T04:01:17Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2021-10-28T10:53:38Z",
          "id": 1,
          "storageBinId": "PVB580_edited_131",
          "storageTypeId": null,
          "uuid": "faebfc42-b7e2-46f6-8ccf-ea653aed3eb6",
          "isDeleted": true
        }
      ],
      "currentPlant": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:18Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-02-21T11:00:53Z",
        "id": 3,
        "mesEP": "",
        "plantId": "BHP",
        "productionProcess": "MTS",
        "name": "Docker Swarm BHP",
        "code": "Test",
        "businessUnit": null,
        "erpId": "6230",
        "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
        "isDeleted": false,
        "npkRounding": true,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:20Z",
        "lastModifiedBy": "admin",
        "lastModifiedDate": "2022-05-31T09:42:19Z",
        "id": 114,
        "identifier": "050 321V",
        "address": "",
        "name": "050 321VXX",
        "active": true,
        "generatePackagingOrders": false,
        "uuid": "aaaa6d67-148a-41de-a906-42060b0db81c",
        "isDeleted": false,
        "plant": {
          "createdBy": "system",
          "createdDate": "2020-08-27T08:41:18Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-02-21T11:00:53Z",
          "id": 3,
          "mesEP": "",
          "plantId": "BHP",
          "productionProcess": "MTS",
          "name": "Docker Swarm BHP",
          "code": "Test",
          "businessUnit": null,
          "erpId": "6230",
          "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
          "isDeleted": false,
          "npkRounding": true,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": [],
      "destinationProductionSupplyArea": null,
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "PLANNED",
    "confirmedUnplanned": null,
    "manualPullDecision": "NONE",
    "product": {
      "createdBy": "admin",
      "createdDate": "2020-02-10T15:32:51Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2020-08-22T12:34:43Z",
      "id": 1731,
      "partNumber": "0261S102X2V87",
      "description": "EL-STEUERGERÄT; MG1CS024",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": null,
      "panelSize": null,
      "packagingMaterial": "0261S102X2V87",
      "packagingSize": null,
      "targetTime": 0,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": null,
      "quantityUnit": null,
      "materialType": null,
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": null,
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 432000000,
    "producedQuantity": 269,
    "entityType": "lot"
  },
  {
    "createdBy": "admin",
    "createdDate": "2020-09-24T14:01:24Z",
    "lastModifiedBy": "system",
    "lastModifiedDate": "2020-09-24T14:51:53Z",
    "id": 26464,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "IN_PRODUCTION",
    "plannedQuantity": 192,
    "actualQuantity": 300,
    "surplusQuantity": 0,
    "failureQuantity": null,
    "dueDate": "2020-09-28T14:01:24Z",
    "plannedStart": "2020-09-24T14:01:24Z",
    "plannedEnd": "2020-09-28T14:01:24Z",
    "actualStart": "2020-09-24T14:05:09Z",
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": true,
    "orderNumber": null,
    "orderSequence": null,
    "workStep": null,
    "changeOverDuration": null,
    "updatedStartTime": "2020-09-24T14:05:09Z",
    "updatedEndTime": "2020-09-28T14:01:26Z",
    "stateChangeTimeStamp": "2020-09-24T14:01:28Z",
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-09-24T14:01:21Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2021-10-28T10:53:35Z",
      "id": 97,
      "lineId": "line 3",
      "name": "line 3",
      "description": "Benchmark Line line 3",
      "active": true,
      "minFifo": 0,
      "maxFifo": 0,
      "sourceId": "line 3",
      "erpId": "",
      "externalPlanning": true,
      "checkByStorageTypeId": null,
      "storageTypeId": null,
      "uuid": "4416d988-8531-4aa6-b063-4f245047a86e",
      "materialOrderService": false,
      "isDeleted": true,
      "productionVersion": "",
      "productionSupplyAreas": [
        {
          "createdBy": "admin",
          "createdDate": "2020-04-29T04:01:17Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2021-10-28T10:53:38Z",
          "id": 1,
          "storageBinId": "PVB580_edited_131",
          "storageTypeId": null,
          "uuid": "faebfc42-b7e2-46f6-8ccf-ea653aed3eb6",
          "isDeleted": true
        }
      ],
      "currentPlant": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:18Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-02-21T11:00:53Z",
        "id": 3,
        "mesEP": "",
        "plantId": "BHP",
        "productionProcess": "MTS",
        "name": "Docker Swarm BHP",
        "code": "Test",
        "businessUnit": null,
        "erpId": "6230",
        "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
        "isDeleted": false,
        "npkRounding": true,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:20Z",
        "lastModifiedBy": "admin",
        "lastModifiedDate": "2022-05-31T09:42:19Z",
        "id": 114,
        "identifier": "050 321V",
        "address": "",
        "name": "050 321VXX",
        "active": true,
        "generatePackagingOrders": false,
        "uuid": "aaaa6d67-148a-41de-a906-42060b0db81c",
        "isDeleted": false,
        "plant": {
          "createdBy": "system",
          "createdDate": "2020-08-27T08:41:18Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-02-21T11:00:53Z",
          "id": 3,
          "mesEP": "",
          "plantId": "BHP",
          "productionProcess": "MTS",
          "name": "Docker Swarm BHP",
          "code": "Test",
          "businessUnit": null,
          "erpId": "6230",
          "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
          "isDeleted": false,
          "npkRounding": true,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": [],
      "destinationProductionSupplyArea": null,
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "PLANNED",
    "confirmedUnplanned": null,
    "manualPullDecision": "NONE",
    "product": {
      "createdBy": "admin",
      "createdDate": "2020-02-10T15:33:59Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2020-08-22T12:34:30Z",
      "id": 1902,
      "partNumber": "0261S102WW133",
      "description": "EL-STEUERGERÄT; MG1CS024",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": null,
      "panelSize": null,
      "packagingMaterial": "0261S102WW133",
      "packagingSize": null,
      "targetTime": 0,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": null,
      "quantityUnit": null,
      "materialType": null,
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": null,
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 345600000,
    "producedQuantity": 300,
    "entityType": "lot"
  },
  {
    "createdBy": "admin",
    "createdDate": "2020-09-25T06:24:04Z",
    "lastModifiedBy": "admin",
    "lastModifiedDate": "2020-09-25T06:24:08Z",
    "id": 26478,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "IN_PREPARATION",
    "plannedQuantity": 272,
    "actualQuantity": 0,
    "surplusQuantity": 0,
    "failureQuantity": 0,
    "dueDate": "2020-09-30T06:24:04Z",
    "plannedStart": "2020-09-25T06:24:04Z",
    "plannedEnd": "2020-09-30T06:24:04Z",
    "actualStart": "2020-09-25T06:24:04Z",
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": true,
    "orderNumber": null,
    "orderSequence": null,
    "workStep": null,
    "changeOverDuration": null,
    "updatedStartTime": "2020-09-25T06:24:06Z",
    "updatedEndTime": "2020-09-30T06:24:06Z",
    "stateChangeTimeStamp": "2020-09-25T06:24:08Z",
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-09-24T08:58:35Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2022-05-31T09:22:18Z",
      "id": 94,
      "lineId": "Line 1",
      "name": "Line 1",
      "description": "",
      "active": true,
      "minFifo": 0,
      "maxFifo": 0,
      "sourceId": "line 1",
      "erpId": "",
      "externalPlanning": false,
      "checkByStorageTypeId": null,
      "storageTypeId": null,
      "uuid": "ef0509a5-278c-435d-87fc-f01bdbe0f9c0",
      "materialOrderService": false,
      "isDeleted": false,
      "productionVersion": "",
      "productionSupplyAreas": [
        {
          "createdBy": "admin",
          "createdDate": "2020-04-29T04:01:17Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2021-10-28T10:53:38Z",
          "id": 1,
          "storageBinId": "PVB580_edited_131",
          "storageTypeId": null,
          "uuid": "faebfc42-b7e2-46f6-8ccf-ea653aed3eb6",
          "isDeleted": true
        }
      ],
      "currentPlant": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:18Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-02-21T11:00:53Z",
        "id": 3,
        "mesEP": "",
        "plantId": "BHP",
        "productionProcess": "MTS",
        "name": "Docker Swarm BHP",
        "code": "Test",
        "businessUnit": null,
        "erpId": "6230",
        "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
        "isDeleted": false,
        "npkRounding": true,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "system",
        "createdDate": "2021-11-29T07:59:48Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2021-11-29T07:59:48Z",
        "id": 1292,
        "identifier": "Irina",
        "address": "",
        "name": "Irina",
        "active": true,
        "generatePackagingOrders": false,
        "uuid": "6ebb1c35-6b27-40e8-9b5b-d0634cdc66bb",
        "isDeleted": false,
        "plant": {
          "createdBy": "system",
          "createdDate": "2020-08-27T08:41:18Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-02-21T11:00:53Z",
          "id": 3,
          "mesEP": "",
          "plantId": "BHP",
          "productionProcess": "MTS",
          "name": "Docker Swarm BHP",
          "code": "Test",
          "businessUnit": null,
          "erpId": "6230",
          "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
          "isDeleted": false,
          "npkRounding": true,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": [],
      "destinationProductionSupplyArea": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:37Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2021-07-30T11:35:10Z",
        "id": 58,
        "storageBinId": "PVBH9_ROH_edited_59",
        "storageTypeId": null,
        "uuid": "b6f8bdb7-3597-49aa-9798-edf3115c1cfb",
        "isDeleted": false
      },
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "PLANNED",
    "confirmedUnplanned": null,
    "manualPullDecision": "NONE",
    "product": {
      "createdBy": "admin",
      "createdDate": "2020-02-10T15:24:22Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2020-05-04T18:34:28Z",
      "id": 460,
      "partNumber": "0261S1000L16B",
      "description": "EL-STEUERGERÄT; MG1CS201",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": null,
      "panelSize": null,
      "packagingMaterial": "0261S1000L16B",
      "packagingSize": null,
      "targetTime": 0,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": null,
      "quantityUnit": null,
      "materialType": null,
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": null,
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 432000000,
    "producedQuantity": 0,
    "entityType": "lot"
  },
  {
    "createdBy": "admin",
    "createdDate": "2020-09-25T06:29:06Z",
    "lastModifiedBy": "admin",
    "lastModifiedDate": "2020-09-25T06:29:11Z",
    "id": 26493,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "IN_PREPARATION",
    "plannedQuantity": 106,
    "actualQuantity": 0,
    "surplusQuantity": 0,
    "failureQuantity": 0,
    "dueDate": "2020-09-29T06:29:05Z",
    "plannedStart": "2020-09-25T06:29:05Z",
    "plannedEnd": "2020-09-29T06:29:05Z",
    "actualStart": "2020-09-25T06:29:05Z",
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": true,
    "orderNumber": null,
    "orderSequence": null,
    "workStep": null,
    "changeOverDuration": null,
    "updatedStartTime": "2020-09-25T06:29:08Z",
    "updatedEndTime": "2020-09-29T06:29:08Z",
    "stateChangeTimeStamp": "2020-09-25T06:29:11Z",
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-09-24T08:58:35Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2022-05-31T09:22:18Z",
      "id": 94,
      "lineId": "Line 1",
      "name": "Line 1",
      "description": "",
      "active": true,
      "minFifo": 0,
      "maxFifo": 0,
      "sourceId": "line 1",
      "erpId": "",
      "externalPlanning": false,
      "checkByStorageTypeId": null,
      "storageTypeId": null,
      "uuid": "ef0509a5-278c-435d-87fc-f01bdbe0f9c0",
      "materialOrderService": false,
      "isDeleted": false,
      "productionVersion": "",
      "productionSupplyAreas": [
        {
          "createdBy": "admin",
          "createdDate": "2020-04-29T04:01:17Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2021-10-28T10:53:38Z",
          "id": 1,
          "storageBinId": "PVB580_edited_131",
          "storageTypeId": null,
          "uuid": "faebfc42-b7e2-46f6-8ccf-ea653aed3eb6",
          "isDeleted": true
        }
      ],
      "currentPlant": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:18Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-02-21T11:00:53Z",
        "id": 3,
        "mesEP": "",
        "plantId": "BHP",
        "productionProcess": "MTS",
        "name": "Docker Swarm BHP",
        "code": "Test",
        "businessUnit": null,
        "erpId": "6230",
        "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
        "isDeleted": false,
        "npkRounding": true,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "system",
        "createdDate": "2021-11-29T07:59:48Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2021-11-29T07:59:48Z",
        "id": 1292,
        "identifier": "Irina",
        "address": "",
        "name": "Irina",
        "active": true,
        "generatePackagingOrders": false,
        "uuid": "6ebb1c35-6b27-40e8-9b5b-d0634cdc66bb",
        "isDeleted": false,
        "plant": {
          "createdBy": "system",
          "createdDate": "2020-08-27T08:41:18Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-02-21T11:00:53Z",
          "id": 3,
          "mesEP": "",
          "plantId": "BHP",
          "productionProcess": "MTS",
          "name": "Docker Swarm BHP",
          "code": "Test",
          "businessUnit": null,
          "erpId": "6230",
          "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
          "isDeleted": false,
          "npkRounding": true,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": [],
      "destinationProductionSupplyArea": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:37Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2021-07-30T11:35:10Z",
        "id": 58,
        "storageBinId": "PVBH9_ROH_edited_59",
        "storageTypeId": null,
        "uuid": "b6f8bdb7-3597-49aa-9798-edf3115c1cfb",
        "isDeleted": false
      },
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "PLANNED",
    "confirmedUnplanned": null,
    "manualPullDecision": "NONE",
    "product": {
      "createdBy": "admin",
      "createdDate": "2020-02-10T15:26:13Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2020-05-04T18:35:32Z",
      "id": 767,
      "partNumber": "0261S1005D14B",
      "description": "EL-STEUERGERÄT; MG1CS201",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": null,
      "panelSize": null,
      "packagingMaterial": "0261S1005D14B",
      "packagingSize": null,
      "targetTime": 0,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": null,
      "quantityUnit": null,
      "materialType": null,
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": null,
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 345600000,
    "producedQuantity": 0,
    "entityType": "lot"
  },
  {
    "createdBy": "admin",
    "createdDate": "2020-09-25T06:44:38Z",
    "lastModifiedBy": "admin",
    "lastModifiedDate": "2020-12-02T02:07:00Z",
    "id": 26510,
    "priority": null,
    "replenishmentType": "HR",
    "lotAssignmentStatus": "IN_PREPARATION",
    "plannedQuantity": 84,
    "actualQuantity": 15,
    "surplusQuantity": 0,
    "failureQuantity": 0,
    "dueDate": "2020-09-29T06:44:37Z",
    "plannedStart": "2020-09-25T06:44:37Z",
    "plannedEnd": "2020-09-29T06:44:37Z",
    "actualStart": "2020-09-25T06:44:37Z",
    "actualEnd": null,
    "sequenceNumber": null,
    "sequenceNumberOriginal": null,
    "fixed": true,
    "orderNumber": null,
    "orderSequence": null,
    "workStep": null,
    "changeOverDuration": null,
    "updatedStartTime": "2020-12-04T02:06:52Z",
    "updatedEndTime": "2020-12-08T02:06:52Z",
    "stateChangeTimeStamp": "2020-09-25T06:44:42Z",
    "productionOrderNumber": null,
    "productionVersionId": null,
    "line": {
      "createdBy": "admin",
      "createdDate": "2020-09-24T08:58:35Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2022-05-31T09:22:18Z",
      "id": 94,
      "lineId": "Line 1",
      "name": "Line 1",
      "description": "",
      "active": true,
      "minFifo": 0,
      "maxFifo": 0,
      "sourceId": "line 1",
      "erpId": "",
      "externalPlanning": false,
      "checkByStorageTypeId": null,
      "storageTypeId": null,
      "uuid": "ef0509a5-278c-435d-87fc-f01bdbe0f9c0",
      "materialOrderService": false,
      "isDeleted": false,
      "productionVersion": "",
      "productionSupplyAreas": [
        {
          "createdBy": "admin",
          "createdDate": "2020-04-29T04:01:17Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2021-10-28T10:53:38Z",
          "id": 1,
          "storageBinId": "PVB580_edited_131",
          "storageTypeId": null,
          "uuid": "faebfc42-b7e2-46f6-8ccf-ea653aed3eb6",
          "isDeleted": true
        }
      ],
      "currentPlant": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:18Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2022-02-21T11:00:53Z",
        "id": 3,
        "mesEP": "",
        "plantId": "BHP",
        "productionProcess": "MTS",
        "name": "Docker Swarm BHP",
        "code": "Test",
        "businessUnit": null,
        "erpId": "6230",
        "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
        "isDeleted": false,
        "npkRounding": true,
        "storageLocationId": null,
        "warehouseId": null
      },
      "workshop": {
        "createdBy": "system",
        "createdDate": "2021-11-29T07:59:48Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2021-11-29T07:59:48Z",
        "id": 1292,
        "identifier": "Irina",
        "address": "",
        "name": "Irina",
        "active": true,
        "generatePackagingOrders": false,
        "uuid": "6ebb1c35-6b27-40e8-9b5b-d0634cdc66bb",
        "isDeleted": false,
        "plant": {
          "createdBy": "system",
          "createdDate": "2020-08-27T08:41:18Z",
          "lastModifiedBy": "system",
          "lastModifiedDate": "2022-02-21T11:00:53Z",
          "id": 3,
          "mesEP": "",
          "plantId": "BHP",
          "productionProcess": "MTS",
          "name": "Docker Swarm BHP",
          "code": "Test",
          "businessUnit": null,
          "erpId": "6230",
          "uuid": "1156ee35-e2e8-40f7-9c4f-e4a92ceb3a0d",
          "isDeleted": false,
          "npkRounding": true,
          "storageLocationId": null,
          "warehouseId": null
        },
        "excludeOrderStatus": null,
        "includeOrderStatus": null,
        "orderTypes": null,
        "productTypes": [],
        "planningBehavior": null,
        "externalProcurement": null,
        "planningBase": null,
        "pacemakerPosition": null
      },
      "productionSubStatuses": [],
      "destinationProductionSupplyArea": {
        "createdBy": "system",
        "createdDate": "2020-08-27T08:41:37Z",
        "lastModifiedBy": "system",
        "lastModifiedDate": "2021-07-30T11:35:10Z",
        "id": 58,
        "storageBinId": "PVBH9_ROH_edited_59",
        "storageTypeId": null,
        "uuid": "b6f8bdb7-3597-49aa-9798-edf3115c1cfb",
        "isDeleted": false
      },
      "preProductionAvailabilityPSAs": [],
      "transportDestinationPsa": null
    },
    "source": "PLANNED",
    "confirmedUnplanned": null,
    "manualPullDecision": "NONE",
    "product": {
      "createdBy": "admin",
      "createdDate": "2020-02-10T15:30:13Z",
      "lastModifiedBy": "system",
      "lastModifiedDate": "2020-08-22T12:28:19Z",
      "id": 1386,
      "partNumber": "0261S101U221B",
      "description": "EL-STEUERGERÄT; MG1CS003",
      "replenishmentType": null,
      "numberPerKanban": null,
      "kanbanQuantity": null,
      "lotSize": null,
      "panelSize": null,
      "packagingMaterial": "0261S101U221B",
      "packagingSize": null,
      "targetTime": 0,
      "planningTime": null,
      "colorCode": null,
      "customer": null,
      "active": true,
      "isMaterialOrdering": false,
      "baseUnitOfMeasure": null,
      "quantityUnit": null,
      "materialType": null,
      "productFamily": null,
      "productIdentification": null,
      "stock": null
    },
    "lotFormation": null,
    "interventionLimit": null,
    "lotNetId": null,
    "productionProcessDetails": null,
    "erpidentifier": null,
    "plannedDurationInMilliSeconds": 345600000,
    "producedQuantity": 15,
    "entityType": "lot"
  }
];


const assigningData = lotAssignments.map((x, i) => ({
  lotNetId: 2908202201,
  ERPIdentifier: "Test-SmartID",
  lotAssignmentStatus: "PLANNED"
}));

const getFormatedData = () => {
  const newData = lotAssignments.map((x, i) => Object.assign(x, assigningData[i]));
  newData.forEach(x=>{
    x.id = null;
  });
  console.log({ newData });
  return newData;
};

const MyCompo = (props) => {
  const [state, setState] = useMergeState({
    data: [],
  });
  const { className } = props;
  const onChange = (key, value) => {
    setState({ [key]: value });
  };
  return (
    <div className={classnames("-wrapper", className)}>
      <span>my component</span>
    </div>
  );
};
MyCompo.defaultProps = {
  className: "",
};
MyCompo.propTypes = {
  className: PropTypes.string,
};

export default MyCompo;
